(()=>{const cfg=window.BASKETBALL_BACKUP_CONFIG,te=new TextEncoder(),td=new TextDecoder();let timer,globalRows=[];const q=s=>document.querySelector(s),b64=b=>btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''),unb64=s=>Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0)),headers=(extra={})=>({apikey:cfg.key,Authorization:`Bearer ${cfg.key}`,'Content-Type':'application/json',...extra}),status=t=>q('#backupStatus').textContent=t;
function migrate(){state.schemaVersion=Math.max(state.schemaVersion||1,3);state.groups||={};state.profileMeta||={};state.profiles.forEach(n=>{state.groups[n]||='Sonstige';state.profileMeta[n]||={id:crypto.randomUUID(),token:b64(crypto.getRandomValues(new Uint8Array(32)))}})}
const points=n=>Object.entries(state.done[n]||{}).reduce((s,[k,v])=>v?s+(exercise[+k.split('-').pop()]?.[2]||0):s,0),meta=()=>JSON.parse(localStorage.getItem('basketball-cloud-backup')||'null');function setMeta(x){localStorage.setItem('basketball-cloud-backup',JSON.stringify(x));showCode()}
async function crypt(payload,secret){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await crypto.subtle.importKey('raw',unb64(secret),'AES-GCM',false,['encrypt']),data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,te.encode(JSON.stringify(payload))));return{ciphertext:b64(data),iv:b64(iv)}}async function decrypt(row,secret){const key=await crypto.subtle.importKey('raw',unb64(secret),'AES-GCM',false,['decrypt']),data=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(row.iv)},key,unb64(row.ciphertext));return JSON.parse(td.decode(data))}
function showCode(){const m=meta();q('#recoveryCode').value=m?`${m.id}.${m.secret}`:'';q('#cloudBackupButton').disabled=!m}
async function backup(){const m=meta();if(!m)return;status('Sicherung läuft …');try{const safe={schemaVersion:state.schemaVersion,profiles:state.profiles,active:state.active,done:state.done,groups:state.groups,profileMeta:state.profileMeta};const e=await crypt(safe,m.secret),r=await fetch(`${cfg.url}/rest/v1/fitness_backups?on_conflict=backup_id`,{method:'POST',headers:headers({Prefer:'resolution=merge-duplicates'}),body:JSON.stringify({backup_id:m.id,...e,app_version:state.schemaVersion,updated_at:new Date().toISOString()})});if(!r.ok)throw 0;status(`Zuletzt gesichert: ${new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`)}catch{status('Cloud-Sicherung noch nicht verfügbar – SQL-Einrichtung prüfen.')}}
async function syncRanking(){migrate();try{await Promise.all(state.profiles.map(n=>fetch(`${cfg.url}/rest/v1/rpc/upsert_fitness_ranking`,{method:'POST',headers:headers(),body:JSON.stringify({p_profile_id:state.profileMeta[n].id,p_owner_token:state.profileMeta[n].token,p_display_name:n,p_group_name:state.groups[n]||'Sonstige',p_total_points:points(n)})})));const r=await fetch(`${cfg.url}/rest/v1/fitness_rankings?select=profile_id,display_name,group_name,total_points,updated_at&order=total_points.desc`,{headers:headers()});if(!r.ok)throw 0;globalRows=await r.json();render()}catch{globalRows=[]}}
function globalRanking(){if(!globalRows.length)return;const order=['U12.1','U14.1','Eltern','Sonstige'];q('#ranking').innerHTML=order.map(g=>{const rows=globalRows.filter(x=>x.group_name===g);return rows.length?`<section class="rank-group"><h3>${g}</h3>${rows.map((x,i)=>`<div class="rank"><b>${i+1}.</b><span class="cloud-avatar">🏀</span><strong>${x.display_name}</strong><strong>${x.total_points} P</strong></div>`).join('')}</section>`:''}).join('')}
const originalRender=render;render=function(){originalRender();globalRanking()};const originalStore=store;store=function(){migrate();originalStore();schedule()};function schedule(){clearTimeout(timer);timer=setTimeout(()=>{backup();syncRanking()},1200)}
q('#createBackupButton').onclick=()=>{if(!meta())setMeta({id:crypto.randomUUID(),secret:b64(crypto.getRandomValues(new Uint8Array(32)))});backup()};q('#cloudBackupButton').onclick=backup;q('#copyCodeButton').onclick=async()=>{const v=q('#recoveryCode').value;if(v){await navigator.clipboard.writeText(v);status('Wiederherstellungscode kopiert.')}};
q('#restoreCloudButton').onclick=async()=>{const p=q('#restoreCode').value.trim().split('.');if(p.length!==2)return status('Code ist nicht gültig.');status('Sicherung wird geladen …');try{const r=await fetch(`${cfg.url}/rest/v1/fitness_backups?backup_id=eq.${encodeURIComponent(p[0])}&select=ciphertext,iv`,{headers:headers()}),rows=await r.json();if(!r.ok||!rows[0])throw 0;const cloud=await decrypt(rows[0],p[1]);state.profiles=[...new Set([...state.profiles,...(cloud.profiles||[])])];for(const[n,d]of Object.entries(cloud.done||{})){state.done[n]||={};for(const[k,v]of Object.entries(d))if(v)state.done[n][k]=true}state.groups={...(cloud.groups||{}),...state.groups};state.profileMeta={...(cloud.profileMeta||{}),...state.profileMeta};migrate();setMeta({id:p[0],secret:p[1]});originalStore();render();schedule();status('Sicherung zusammengeführt – vorhandene Häkchen blieben erhalten.')}catch{status('Sicherung nicht gefunden oder Code falsch.')}};
migrate();originalStore();showCode();syncRanking();if(meta())schedule()})();
