state.photos ||= {};state.groups ||= {};state.profiles.forEach(n=>state.groups[n]||='Sonstige');
const avatar=n=>state.photos[n]?`<img class="avatar" src="${state.photos[n]}" alt="">`:'👤';
const total=n=>Object.entries(state.done[n]||{}).reduce((s,[k,v])=>v?s+(exercise[+k.split('-').pop()]?.[2]||0):s,0);
const groupOrder=['U12.1','U14.1','Eltern','Sonstige'];
const baseRender=render;render=function(){baseRender();const groups=groupOrder.map(g=>{const members=[...state.profiles].filter(n=>state.groups[n]===g).sort((a,b)=>total(b)-total(a));return members.length?`<section class="rank-group"><h3>${g}</h3>${members.map((n,i)=>`<div class="rank"><b>${i+1}.</b>${avatar(n)}<strong>${n}</strong><strong>${total(n)} P</strong></div>`).join('')}</section>`:''}).join('');$('#ranking').innerHTML=groups;$('#profileButton span').innerHTML=`${avatar(state.active)} ${state.active}`};
async function removeGlobalProfile(n){const cfg=window.BASKETBALL_BACKUP_CONFIG,m=state.profileMeta?.[n];if(!cfg||!m)return;try{await fetch(`${cfg.url}/rest/v1/rpc/delete_fitness_ranking`,{method:'POST',headers:{apikey:cfg.key,Authorization:`Bearer ${cfg.key}`,'Content-Type':'application/json'},body:JSON.stringify({p_profile_id:m.id,p_owner_token:m.token})})}catch{}}
function renameProfile(oldName){const newName=prompt('Neuer Name:',oldName)?.trim();if(!newName||newName===oldName)return;if(state.profiles.includes(newName))return alert('Dieser Name ist bereits vorhanden.');state.profiles=state.profiles.map(n=>n===oldName?newName:n);for(const key of ['done','groups','photos','profileMeta'])if(state[key]?.[oldName]!==undefined){state[key][newName]=state[key][oldName];delete state[key][oldName]}state.active=newName;store();profiles();render()}
async function deleteProfile(n){if(state.profiles.length===1)return alert('Mindestens ein Profil muss erhalten bleiben.');if(!confirm(`${n} und den gesamten Fortschritt wirklich löschen?`))return;await removeGlobalProfile(n);state.profiles=state.profiles.filter(x=>x!==n);for(const key of ['done','groups','photos','profileMeta'])if(state[key])delete state[key][n];if(state.active===n)state.active=state.profiles[0];store();profiles();render()}
const baseProfiles=profiles;profiles=function(){baseProfiles();$('#photoName').textContent=state.active;$('#groupSelect').value=state.groups[state.active]||'Sonstige';document.querySelectorAll('.profile-row').forEach(row=>{const main=row.querySelector('button[data-name]'),n=main.dataset.name;main.innerHTML=`${avatar(n)} <span>${n}<small>${state.groups[n]||'Sonstige'}</small></span>`;const edit=document.createElement('button');edit.type='button';edit.className='profile-action';edit.textContent='✏️';edit.onclick=()=>renameProfile(n);const del=document.createElement('button');del.type='button';del.className='profile-action danger-mini';del.textContent='🗑️';del.onclick=()=>deleteProfile(n);row.append(edit,del)})};
$('#groupSelect').onchange=e=>{state.groups[state.active]=e.target.value;store();profiles();render()};
$('#addProfile').onclick=()=>{const n=$('#newProfile').value.trim();if(n&&!state.profiles.includes(n)){state.profiles.push(n);state.active=n;state.groups[n]=$('#newGroup').value;$('#newProfile').value='';store();profiles();render()}};
$('#photoInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const img=new Image();img.src=URL.createObjectURL(f);await img.decode();const c=document.createElement('canvas');c.width=c.height=180;const x=c.getContext('2d'),s=Math.min(img.width,img.height);x.drawImage(img,(img.width-s)/2,(img.height-s)/2,s,s,0,0,180,180);state.photos[state.active]=c.toDataURL('image/jpeg',.75);URL.revokeObjectURL(img.src);store();profiles();render();e.target.value=''};store();render();
