(()=>{
const cfg=window.BASKETBALL_BACKUP_CONFIG||{},sessionKey='basketball-trainer-test-session';
const names=['Dribbeln vor dem Körper','Dribbeln hinter dem Körper','Durch die Beine dribbeln','Achter durch die Beine dribbeln','Seitlich vor dem Körper dribbeln','3 km laufen','Liegestütze','Breite Liegestütze','Enge Liegestütze','Sit-ups','Ausfallschritte vor/zurück','Kniebeugen normal','Kniebeugen breit','Froschsprünge','Tiefe & hohe Sprünge','Planke','Korbleger links/rechts'];
const fallbackPoints=[3,3,3,3,3,10,3,3,3,3,2,2,2,2,4,5,6];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[];
function session(){try{return JSON.parse(sessionStorage.getItem(sessionKey)||'null')}catch{return null}}
function setSession(value){value?sessionStorage.setItem(sessionKey,JSON.stringify(value)):sessionStorage.removeItem(sessionKey)}
function week(date){const start=new Date('2026-07-20T12:00:00'),d=new Date(`${date}T12:00:00`);return Math.max(1,Math.min(6,Math.floor((d-start)/604800000)+1))}
function target(id,date){const w=week(date);if(id<=4)return'20 Sekunden';if(id===5)return'Weiter als in der Vorwoche';if(id>=6&&id<=13)return`${10+(w-1)*5} Wiederholungen`;if(id===14)return`${30+(w-1)*5} Sekunden · 3× tief, 2× hoch`;if(id===15)return`${20+(w-1)*10} Sekunden`;if(id===16)return`${10+(w-1)*2} Treffer am Stück`;return''}
function dateLabel(date){return new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${date}T12:00:00`))}
function timeLabel(value){return value?new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Berlin'}).format(new Date(value)):'–'}
function configured(){return Boolean(cfg.url&&cfg.key&&!cfg.testMode)}
function showAuthenticated(ok){$('#loginPanel').hidden=ok;$('#reportPanel').hidden=!ok}
async function login(email,password){const response=await fetch(`${cfg.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const body=await response.json().catch(()=>({}));if(!response.ok||!body.access_token)throw new Error(body.error_description||body.msg||'Anmeldung fehlgeschlagen.');setSession({access_token:body.access_token,email:body.user?.email||email});showAuthenticated(true);await loadReport()}
async function callReport(date){const s=session();if(!s?.access_token)throw new Error('Bitte erneut anmelden.');const response=await fetch(`${cfg.url}/rest/v1/rpc/get_fitness_daily_report`,{method:'POST',headers:{apikey:cfg.key,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({p_report_date:date})});const body=await response.json().catch(()=>[]);if(response.status===401){setSession(null);showAuthenticated(false)}if(!response.ok)throw new Error(body.message||'Übersicht konnte nicht geladen werden.');return body}
function render(date){const completed=rows.filter(r=>r.exercise_id!==null),byProfile=new Map();for(const row of rows){const item=byProfile.get(row.profile_id)||{name:row.display_name,group:row.group_name,count:0,total:0};if(row.exercise_id!==null){item.count++;item.total+=Number(row.points||0)}byProfile.set(row.profile_id,item)}const groups=['U12.1','U14.1','Eltern','Sonstige'];$('#reportTitle').textContent=dateLabel(date);$('#reportTotal').textContent=`${completed.reduce((sum,r)=>sum+Number(r.points||0),0)} Punkte`;$('#summary').innerHTML=groups.map(group=>{const members=[...byProfile.values()].filter(x=>x.group===group);if(!members.length)return'';return`<article><h3>${esc(group)}</h3><p>${members.length} Profile</p><p>${members.reduce((s,x)=>s+x.count,0)} Aufgaben · ${members.reduce((s,x)=>s+x.total,0)} Punkte</p></article>`}).join('');$('#reportRows').innerHTML=rows.length?rows.map(row=>row.exercise_id===null?`<tr><td>${esc(row.group_name)}</td><td>${esc(row.display_name)}</td><td class="none">Noch keine Aufgabe</td><td>–</td><td>0</td><td>–</td></tr>`:`<tr><td>${esc(row.group_name)}</td><td>${esc(row.display_name)}</td><td>${esc(names[row.exercise_id]||`Aufgabe ${row.exercise_id}`)}</td><td>${esc(target(Number(row.exercise_id),date))}</td><td>${Number(row.points||fallbackPoints[row.exercise_id]||0)}</td><td>${esc(timeLabel(row.completed_at))}</td></tr>`).join(''):'<tr><td colspan="6">Keine Profile vorhanden.</td></tr>'}
async function loadReport(){const date=$('#reportDate').value;$('#reportRows').innerHTML='<tr><td colspan="6">Übersicht wird geladen …</td></tr>';try{rows=await callReport(date);render(date)}catch(error){$('#reportRows').innerHTML=`<tr><td colspan="6">${esc(error.message)}</td></tr>`}}
function csvCell(value){return`"${String(value??'').replaceAll('"','""')}"`}
function download(){const date=$('#reportDate').value,lines=[['Trainingstag','Gruppe','Name','Aufgabe','Leistung','Punkte','Eingetragen'].map(csvCell).join(';')];for(const row of rows)lines.push([date,row.group_name,row.display_name,row.exercise_id===null?'Noch keine Aufgabe':names[row.exercise_id],row.exercise_id===null?'':target(Number(row.exercise_id),date),row.exercise_id===null?0:row.points,timeLabel(row.completed_at)].map(csvCell).join(';'));const url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`Basketball-Fitness-${date}.csv`;a.click();URL.revokeObjectURL(url)}
const today=new URLSearchParams(location.search).get('testDate')||new Date().toISOString().slice(0,10);$('#reportDate').value=today<'2026-07-18'?'2026-07-18':today>'2026-09-01'?'2026-09-01':today;
if(!configured()){const notice=$('#connectionNotice');notice.hidden=false;notice.textContent='Die Trainerübersicht ist vorbereitet, aber noch nicht mit einer separaten Supabase-Testdatenbank verbunden.';$('#loginForm').querySelector('button').disabled=true}
$('#loginForm').onsubmit=async event=>{event.preventDefault();$('#loginStatus').textContent='Anmeldung läuft …';try{await login($('#email').value.trim(),$('#password').value);$('#loginStatus').textContent=''}catch(error){$('#loginStatus').textContent=error.message}};
$('#loadReport').onclick=loadReport;$('#downloadCsv').onclick=download;$('#printReport').onclick=()=>print();$('#logout').onclick=()=>{setSession(null);showAuthenticated(false)};if(configured()&&session()?.access_token){showAuthenticated(true);loadReport()}
})();
